name: OnStove Functional tests
on:
  push:
    branches: ['actions', 'tests', 'tests_technology']
    paths: ['onstove/*', 'onstove/tests/*']

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["windows-latest"]
            python-version: ["3.10.*"]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: onstove-tests
          environment-file: environment-tests.yml
          auto-activate-base: false

      - name: Run pytest
        env:
            AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
            AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
        shell: bash -l {0}
        run: |
            pytest
